# Generated by Django 4.2.29 on 2026-04-30 05:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0012_playertrendingsnapshot'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='playertrendingsnapshot',
            name='unique_player_trending_per_day',
        ),
        migrations.RenameIndex(
            model_name='aitransactionlog',
            new_name='accounts_ai_user_id_0d8d5b_idx',
            old_name='accounts_ai_user_id_team_created_idx',
        ),
        migrations.RenameIndex(
            model_name='playertrendingsnapshot',
            new_name='accounts_pl_user_id_7ca6cd_idx',
            old_name='pts_user_team_date_idx',
        ),
        migrations.RenameIndex(
            model_name='playertrendingsnapshot',
            new_name='accounts_pl_player__80dcf2_idx',
            old_name='pts_player_date_idx',
        ),
        migrations.AlterField(
            model_name='keptplayer',
            name='kept_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='playertrendingsnapshot',
            unique_together={('user', 'team_key', 'player_key', 'date')},
        ),
    ]
